-- Schema and sample data for the sacrament meeting planner.
-- Run once against your Neon database (e.g. in the Neon SQL editor, or: psql "$DATABASE_URL" -f db/schema.sql).

CREATE TABLE IF NOT EXISTS meetings (
  id             SERIAL PRIMARY KEY,
  date           DATE NOT NULL,
  meeting_type   TEXT NOT NULL CHECK (meeting_type IN ('testimony', 'regular', 'stake', 'general', 'special')),
  presiding      TEXT NOT NULL,
  conducting     TEXT NOT NULL,
  announcements  TEXT[] NOT NULL DEFAULT '{}',
  opening_hymn   JSONB NOT NULL,
  opening_prayer TEXT NOT NULL,
  ward_business  JSONB NOT NULL DEFAULT '[]',
  stake_business BOOLEAN NOT NULL DEFAULT FALSE,
  sacrament_hymn JSONB NOT NULL,
  speakers       JSONB NOT NULL DEFAULT '[]',
  closing_hymn   JSONB NOT NULL,
  closing_prayer TEXT NOT NULL
);

INSERT INTO meetings (
  date, meeting_type, presiding, conducting, announcements, opening_hymn, opening_prayer,
  ward_business, stake_business, sacrament_hymn, speakers, closing_hymn, closing_prayer
) VALUES
  ('2026-08-30',
   'regular',
   'Bishop Daniel Reyes',
   'Brother Samuel Ortega',
   ARRAY['Ward temple night is Thursday, September 3 at 7:00 PM.', 'Youth back-to-school activity Wednesday at the church.'],
   '{"number":2,"title":"The Spirit of God"}'::jsonb,
   'Sister Ana Morales',
   '[{"description":"Release of Sister Laura Kim as Primary pianist, with a vote of thanks."},{"description":"Sustaining of Brother Jacob Price as Sunday School teacher."}]'::jsonb,
   false,
   '{"number":169,"title":"As Now We Take the Sacrament"}'::jsonb,
   '[{"name":"Sister Emily Tanner","topic":"Ministering like the Savior","type":"speaker"},{"name":"Brother Carlos Vega","topic":"Faith in hard times","type":"speaker"},{"name":"Primary children","topic":"I Am a Child of God","type":"musical-number"},{"name":"Brother Samuel Ortega","topic":"The blessings of covenants","type":"speaker"}]'::jsonb,
   '{"number":85,"title":"How Firm a Foundation"}'::jsonb,
   'Brother Thomas Lee'),
  ('2026-09-06',
   'testimony',
   'Bishop Daniel Reyes',
   'Bishop Daniel Reyes',
   ARRAY['Fast offerings may be given to any member of the bishopric.'],
   '{"number":19,"title":"We Thank Thee, O God, for a Prophet"}'::jsonb,
   'Sister Grace Walker',
   '[{"description":"Confirmation of Olivia Martinez as a member of the Church."},{"description":"Baby blessing: Noah James Harris."}]'::jsonb,
   false,
   '{"number":193,"title":"I Stand All Amazed"}'::jsonb,
   '[]'::jsonb,
   '{"number":136,"title":"I Know That My Redeemer Lives"}'::jsonb,
   'Brother David Nguyen'),
  ('2026-09-13',
   'stake',
   'President Robert Allen, Stake President',
   'President James Holt, First Counselor',
   ARRAY['Stake conference is held at the stake center; there are no ward meetings today.'],
   '{"number":3,"title":"Now Let Us Rejoice"}'::jsonb,
   'Sister Rebecca Young',
   '[]'::jsonb,
   true,
   '{"number":181,"title":"Jesus of Nazareth, Savior and King"}'::jsonb,
   '[{"name":"Sister Hannah Brooks, Stake Relief Society President","topic":"Gathering Israel","type":"speaker"},{"name":"Stake choir","topic":"Come, Thou Fount of Every Blessing","type":"musical-number"},{"name":"President Robert Allen","topic":"Following living prophets","type":"speaker"}]'::jsonb,
   '{"number":27,"title":"Praise to the Man"}'::jsonb,
   'Brother Kevin Wright'),
  ('2026-09-20',
   'regular',
   'Bishop Daniel Reyes',
   'Brother Michael Chen',
   ARRAY['General Conference will be broadcast October 3–4; there will be no ward meetings on October 4.', 'The Relief Society service project is Saturday at 9:00 AM.'],
   '{"number":98,"title":"I Need Thee Every Hour"}'::jsonb,
   'Sister Maria Lopez',
   '[{"description":"Sustaining of Sister Rachel Adams as Young Women president."},{"description":"Ordination of Ethan Clark to the office of priest."}]'::jsonb,
   false,
   '{"number":172,"title":"In Humility, Our Savior"}'::jsonb,
   '[{"name":"Ethan Clark","topic":"Preparing to serve a mission","type":"speaker"},{"name":"Sister Rachel Adams","topic":"Strengthening the rising generation","type":"speaker"},{"name":"Sister Kim and Sister Patel","topic":"Where Can I Turn for Peace?","type":"musical-number"},{"name":"Brother Joseph Bennett","topic":"The Atonement of Jesus Christ","type":"speaker"}]'::jsonb,
   '{"number":301,"title":"I Am a Child of God"}'::jsonb,
   'Brother Andrew Scott'),
  ('2026-09-27',
   'regular',
   'Bishop Daniel Reyes',
   'Brother Samuel Ortega',
   ARRAY['Tithing declaration appointments begin in November; sign-ups are in the foyer.'],
   '{"number":5,"title":"High on the Mountain Top"}'::jsonb,
   'Sister Julia Ramirez',
   '[{"description":"Sustaining of Brother Nathan Hill as ward clerk."}]'::jsonb,
   false,
   '{"number":175,"title":"O God, the Eternal Father"}'::jsonb,
   '[{"name":"Sister Sophia Turner","topic":"Gratitude","type":"speaker"},{"name":"Brother Nathan Hill","topic":"The Book of Mormon","type":"speaker"}]'::jsonb,
   '{"number":152,"title":"God Be with You Till We Meet Again"}'::jsonb,
   'Brother Isaac Moore'),
  ('2026-10-04',
   'general',
   'President of the Church',
   'A member of the First Presidency',
   ARRAY['General Conference Sunday morning session broadcast; no ward sacrament meeting.'],
   '{"number":21,"title":"Come, Listen to a Prophet’s Voice"}'::jsonb,
   'As assigned',
   '[]'::jsonb,
   false,
   '{"number":196,"title":"Jesus, Once of Humble Birth"}'::jsonb,
   '[]'::jsonb,
   '{"number":19,"title":"We Thank Thee, O God, for a Prophet"}'::jsonb,
   'As assigned');
